### ISSUE TITLE
SolidStateDiamond warns that I do not have a receive ether function in my contract

### ISSUE THREAD

**Issue by favoursyre** [solidstate-network/solidstate-solidity#201] opened 2023-03-13 17:02 UTC
I'm trying to implement a Diamond contract using hardhat, when I try to compile the diamond contract, I get the following warning

```bash
Warning: This contract has a payable fallback function, but no receive ether function. Consider adding a receive ether function.
 --> @solidstate/contracts/proxy/diamond/fallback/IDiamondFallback.sol:7:1:
  |
7 | interface IDiamondFallback is IDiamondBase {
  | ^ (Relevant source part starts here and spans across multiple lines).
Note: The payable fallback function is defined here.
 --> @solidstate/contracts/proxy/IProxy.sol:8:5:
  |
8 |     fallback() external payable;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^


Warning: This contract has a payable fallback function, but no receive ether function. Consider adding a receive ether function.
  --> @solidstate/contracts/proxy/diamond/fallback/DiamondFallback.sol:15:1:
   |
15 | abstract contract DiamondFallback is
   | ^ (Relevant source part starts here and spans across multiple lines).
Note: The payable fallback function is defined here.
  --> @solidstate/contracts/proxy/Proxy.sol:19:5:
   |
19 |     fallback() external payable virtual {
   |     ^ (Relevant source part starts here and spans across multiple lines).


Generating typings for: 52 artifacts in dir: typechain-types for target: ethers-v5
Successfully generated 130 typings!
Compiled 52 Solidity files successfully
```

How do I go about solving this issue?

**Comment by 0xCourtney** [comment] 2023-03-13 17:48
Might be best to ignore this or implement a [reverting `receive` function](https://github.com/solidstate-network/solidstate-solidity/issues/200)... Unfortunately, there's [no clean way](https://github.com/ethereum/solidity/issues/10159) to disable this warning.

**Comment by ItsNickBarry** [comment] 2023-03-13 20:47
Duplicate of #200.  I'm not entirely sure why this warning exists.

**Closed by ItsNickBarry** 2023-03-13 20:47 UTC
