### ISSUE TITLE
Add Access Control

### ISSUE THREAD

**Issue by iam-dev** [solidstate-network/solidstate-solidity#94] opened 2022-05-10 18:35 UTC
Add AccessControl Library like Openzeppelin

https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/access/AccessControl.sol

**Comment by ItsNickBarry** [comment] 2022-05-10 18:41
Duplicate of #63.

**Closed by ItsNickBarry** 2022-05-10 18:41 UTC
